name = "VariogramAnalysis"
uuid = "07dc4704-23df-41f7-aa80-c1ad3d8f3e52"
authors = ["msturroc <marcsturrock@protonmail.com>", "Shayan Jalali <shayanjalali@rcsi.ie>"]
repo = "https://github.com/msturroc/VariogramAnalysis.jl.git"
version = "0.3.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Surrogates = "6fc51010-71bc-11e9-0e15-a3fcc6593c49"

[extensions]
VariogramAnalysisBlackBoxOptimExt = ["BlackBoxOptim", "DataFrames"]
VariogramAnalysisSurrogatesExt = ["DataFrames", "Surrogates"]

[compat]
Aqua = "0.8"
BlackBoxOptim = "0.6.3"
Combinatorics = "1.0"
DataFrames = "1.7"
Distributions = "0.25"
HCubature = "1.7"
LinearAlgebra = "1.10"
OrderedCollections = "1.8"
ProgressMeter = "1.10"
QuadGK = "2.9"
QuasiMonteCarlo = "0.3"
Random = "1.10"
Roots = "2.2"
Statistics = "1.10"
Surrogates = "6, 7.0.1"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Surrogates = "6fc51010-71bc-11e9-0e15-a3fcc6593c49"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "BlackBoxOptim", "DataFrames", "QuasiMonteCarlo", "Surrogates", "Test"]
