using Statistics, Combinatorics, Distributions

"""
Helper to get the min/max bounds for each parameter for normalization.
"""
function _get_param_bounds(parameters::OrderedDict)
    d = length(parameters)
    xmin = zeros(d)
    xmax = zeros(d)
    param_defs = collect(values(parameters))

    for i in 1:d
        p = param_defs[i]
        dist_type = p.dist
        if dist_type == "unif" || dist_type == "triangle"
            xmin[i], xmax[i] = p.p1, p.p2
        elseif dist_type == "norm"
            # Use 3-sigma rule as in the python code
            xmin[i] = p.p1 - 3 * p.p2
            xmax[i] = p.p1 + 3 * p.p2
        else
            # Fallback for other distributions: use extreme quantiles as effective bounds
            dist, _, _ = VariogramAnalysis._get_distribution_and_stats(p)
            q_low = quantile(dist, 0.001)
            q_high = quantile(dist, 0.999)
            xmin[i], xmax[i] = q_low, q_high
        end
    end
    return xmin, xmax
end

"""
Build an index from (star_id, dim_id) to the positions in `info` belonging to
that group, so the analysis loops avoid rescanning `info` for every star/dim
combination. `groups[star][dim + 1]` holds the indices for dimension `dim`,
with `dim == 0` being the star centre.
"""
function _index_info(info::Vector, N::Int, d::Int)
    groups = [[Int[] for _ in 0:d] for _ in 1:N]
    for (idx, p) in enumerate(info)
        push!(groups[p.star_id][p.dim_id + 1], idx)
    end
    return groups
end


"""
    vars_analyse(Y, info, N, d, delta_h)

Compute total-order VARS sensitivity indices from model outputs `Y` evaluated
on a design generated by [`generate_vars_samples`](@ref).

For every star and dimension, directional variogram and covariogram terms are
estimated from pairs of points one step apart, matching the Python tool's
step-based pairing. `delta_h` is accepted for signature symmetry with
[`gvars_analyse`](@ref); the pairing itself uses the step ids recorded in
`info`.

Returns `(ST = Vector)` with one total-order index per dimension. A dimension
with no usable pairs yields `NaN`; a numerically constant `Y` yields all
zeros.
"""
function vars_analyse(Y::Vector, info::Vector{NamedTuple{(:star_id, :dim_id, :step_id, :h), Tuple{Int, Int, Int, Float64}}}, N::Int, d::Int, delta_h::Float64)
    VY = var(Y)
    if VY < 1e-12
        return (ST = zeros(d),)
    end

    groups = _index_info(info, N, d)

    ST = zeros(d)
    for dim in 1:d
        gamma_sum, ecov_sum, stars_with_data = 0.0, 0.0, 0

        for star in 1:N
            ray_only_indices = groups[star][dim + 1]
            ray_indices = vcat(groups[star][1], ray_only_indices)
            if length(ray_indices) < 2 continue end

            sort!(ray_indices, by = idx -> info[idx].step_id)

            one_step_pairs = Tuple{Float64, Float64}[]
            for k in 1:(length(ray_indices) - 1)
                idx1 = ray_indices[k]
                idx2 = ray_indices[k+1]
                if abs(info[idx1].step_id - info[idx2].step_id) == 1
                    push!(one_step_pairs, (Y[idx1], Y[idx2]))
                end
            end

            if isempty(one_step_pairs) continue end

            p1 = [p[1] for p in one_step_pairs]
            p2 = [p[2] for p in one_step_pairs]

            gamma_i = 0.5 * mean((p1 .- p2).^2)

            y_ray_values = Y[ray_only_indices]
            mu_star = isempty(y_ray_values) ? 0.0 : mean(y_ray_values)

            ecov_i = mean((p1 .- mu_star) .* (p2 .- mu_star))

            gamma_sum += gamma_i
            ecov_sum += ecov_i
            stars_with_data += 1
        end

        ST[dim] = stars_with_data > 0 ? (gamma_sum / stars_with_data + ecov_sum / stars_with_data) / VY : NaN
    end
    return (ST=ST,)
end


"""
    gvars_analyse(Y, X, info, N, d, delta_h, parameters)

G-VARS analysis for correlated inputs. On each star, pairs of points whose
normalised distance along the target dimension falls within `(0, delta_h]`
contribute to the variogram/covariogram estimates, replicating the Python
tool's binning logic. Returns `(ST = Vector)` as in [`vars_analyse`](@ref).
"""
function gvars_analyse(Y::Vector, X::Matrix, info::Vector{NamedTuple{(:star_id, :dim_id, :step_id, :h), Tuple{Int, Int, Int, Float64}}}, N::Int, d::Int, delta_h::Float64, parameters::OrderedDict)
    VY = var(Y)
    if VY < 1e-12
        return (ST = zeros(d),)
    end

    xmin, xmax = _get_param_bounds(parameters)
    param_ranges = xmax .- xmin

    groups = _index_info(info, N, d)

    ST = zeros(d)
    for dim in 1:d
        gamma_sum, ecov_sum, stars_with_data = 0.0, 0.0, 0

        for star in 1:N
            ray_only_indices = groups[star][dim + 1]
            ray_indices = vcat(groups[star][1], ray_only_indices)
            if length(ray_indices) < 2 continue end

            # Collect pairs that fall into the delta_h bin based on normalized distance
            binned_pairs = Tuple{Float64, Float64}[]
            for (idx1, idx2) in combinations(ray_indices, 2)
                # Calculate normalized distance in the original parameter space
                dist = abs(X[dim, idx1] - X[dim, idx2])
                norm_dist = param_ranges[dim] > 1e-9 ? dist / param_ranges[dim] : 0.0

                # Python's binning logic: bin index is floor(norm_dist / delta_h)
                # The target bin for ST is the first one, corresponding to h=delta_h.
                # The python code's binning is a bit tricky, but this logic should be equivalent
                # for the first bin: 0 < norm_dist <= delta_h
                if 0 < norm_dist <= delta_h
                    push!(binned_pairs, (Y[idx1], Y[idx2]))
                end
            end

            if isempty(binned_pairs) continue end

            p1 = [p[1] for p in binned_pairs]
            p2 = [p[2] for p in binned_pairs]

            gamma_i = 0.5 * mean((p1 .- p2).^2)

            y_ray_values = Y[ray_only_indices]
            mu_star = isempty(y_ray_values) ? 0.0 : mean(y_ray_values)

            ecov_i = mean((p1 .- mu_star) .* (p2 .- mu_star))

            gamma_sum += gamma_i
            ecov_sum += ecov_i
            stars_with_data += 1
        end

        ST[dim] = stars_with_data > 0 ? (gamma_sum / stars_with_data + ecov_sum / stars_with_data) / VY : NaN
    end
    return (ST=ST,)
end
